import React from "react";
import "./Slider.css";

const Slider = () => {
  return (
    <div>
      <div className="companies-slider">
        <div className="companies-slider__title">
          <p>Trusted by 130,000 companies in 180+ countries</p>
        </div>
        <div className="companies-slider__inner slick-initialized slick-slider">
          <div className="slick-list">
            <div
              className="slick-track"
              style={{
                opacity: 1,
                width: "55000px",
                transform: "translate3d(-1800px, 0px, 0px)",
                transition: "transform 2800ms linear 0s",
              }}
            >
              <div
                className="slick-slide slick-cloned"
                data-slick-index={-7}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/payoneer.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/payoneer.png"
                        alt="Payoneer"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={-6}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/sendpulse.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/sendpulse.png"
                        alt="SendPulse"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={-5}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/docusign.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/docusign.png"
                        alt="DocuSign picture"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={-4}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/zendesk.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/zendesk.png"
                        alt="Zendesk"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={-3}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/freshworks.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/freshworks.png"
                        alt="Freshworks"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={-2}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/moosend.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/moosend.png"
                        alt="Moosend"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={-1}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/comcast.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/comcast.png"
                        alt="Comcast"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide"
                data-slick-index={0}
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/google.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/google.png"
                        alt="Google"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide"
                data-slick-index={1}
                aria-hidden="true"
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/salesforce.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/salesforce.png"
                        alt="Salesforce"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-current slick-active"
                data-slick-index={2}
                aria-hidden="false"
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/dropbox.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/dropbox.png"
                        alt="Dropbox"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-active"
                data-slick-index={3}
                aria-hidden="false"
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/canva.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/canva.png"
                        alt="Canva"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-active"
                data-slick-index={4}
                aria-hidden="false"
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/payoneer.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/payoneer.png"
                        alt="Payoneer"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-active"
                data-slick-index={5}
                aria-hidden="false"
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/sendpulse.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/sendpulse.png"
                        alt="SendPulse"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-active"
                data-slick-index={6}
                aria-hidden="false"
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/docusign.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/docusign.png"
                        alt="DocuSign"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-active"
                data-slick-index={7}
                aria-hidden="false"
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/zendesk.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/zendesk.png"
                        alt="Zendesk"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-active"
                data-slick-index={8}
                aria-hidden="false"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/freshworks.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/freshworks.png"
                        alt="Freshworks"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide"
                data-slick-index={9}
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/moosend.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/moosend.png"
                        alt="Moosend"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide"
                data-slick-index={10}
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/comcast.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/comcast.png"
                        alt="Comcast"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={11}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/google.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/google.png"
                        alt="Google"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={12}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/salesforce.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/salesforce.png"
                        alt="Salesforce"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={13}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/dropbox.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/dropbox.png"
                        alt="Dropbox"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={14}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/canva.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/canva.png"
                        alt="Canva"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={15}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/payoneer.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/payoneer.png"
                        alt="Payoneer"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={16}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/sendpulse.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/sendpulse.png"
                        alt="SendPulse"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={17}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/docusign.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/docusign.png"
                        alt="DocuSign"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={18}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/zendesk.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/zendesk.png"
                        alt="Zendesk "
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={19}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/freshworks.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/freshworks.png"
                        alt="Freshworks"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={20}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/moosend.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/moosend.png"
                        alt="Moosend"
                        width={200}
                        height={56}
                      />
                    </picture>
                  </div>
                </div>
              </div>
              <div
                className="slick-slide slick-cloned"
                data-slick-index={21}
                id
                aria-hidden="true"
                tabIndex={-1}
              >
                <div>
                  <div
                    className="companies-slider__item"
                    style={{ width: "100%", display: "inline-block" }}
                  >
                    <picture>
                      <source
                        srcSet="https://cdn-landing.snov.io/images/pages/index/slider/comcast.webp"
                        type="image/webp"
                      />
                      <img
                        src="https://cdn-landing.snov.io/images/pages/index/slider/comcast.png"
                        alt="Comcast"
                        width={200}
                        height={56}
                    
                      />
                    </picture>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Slider;
